version: "3.8"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "BankDb202#"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1313:1313" 
    volumes:
      - db_data:/var/opt/mssql/data
  bank-api:
    build: .
    environment:
      CONNECTION_STRING: "Server=database;Initial Catalog=bank;User Id=sa;Password=BankDb202#;Encrypt=False;TrustServerCertificate=True"
      APP_NAME: "TopUp API"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - database
    ports:
      - "8080:80"
volumes:
  db_data:
